### ISSUE TITLE
Rdkit error

### ISSUE THREAD

**Issue by HamzaShaikh17** [ComPlat/chem_scanner#2]
I am running example code snippet that throws an error

(base) hamza@mac Documents % ruby chem.rb               
Traceback (most recent call last):
	2: from chem.rb:1:in `<main>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- chem_scanner (LoadError)
	8: from chem.rb:1:in `<main>'
	7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	4: from /Library/Ruby/Gems/2.6.0/gems/chem_scanner-0.1.3/lib/chem_scanner.rb:2:in `<top (required)>'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	1: from /Library/Ruby/Gems/2.6.0/gems/rdkit_chem-2019.03.3.1/lib/rdkit_chem.rb:1:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rdkit_chem-2019.03.3.1/lib/rdkit_chem.rb:1:in `require_relative': cannot load such file -- /Library/Ruby/Gems/2.6.0/gems/rdkit_chem-2019.03.3.1/rdkit/Code/lib/RDKitChem (LoadError)

After getting this error I have tried to install dependent rdkit library by following command:

gem install rdkit_chem

But it still throwing the same error

is there any solution?

**Comment by CamAnNguyen** [comment]
Hi @HS1S, the `chem_scanner` gem is using [rdkit_chem](https://github.com/CamAnNguyen/rdkit_chem) gem, therefore it requires dependencies of [rdkit_chem](https://github.com/CamAnNguyen/rdkit_chem). Could you please install the required package listed [here](https://github.com/CamAnNguyen/rdkit_chem#prerequisites) and reinstall the gem?
